field: 028f6018-5444-44d0-b254-cfea8e4742e5
fieldLayouts:
  8903b27d-4a64-4695-a9b8-8ab988e2a0cc:
    tabs:
      -
        elements:
          -
            fieldUid: 90922590-58f0-4a7e-abfb-8ca16b15ddef
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 29e35ad8-c407-4d90-bff6-c6d86a8bf862
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  29e35ad8-c407-4d90-bff6-c6d86a8bf862:
    contentColumnType: text
    fieldGroup: null
    handle: descriptionNetwork
    instructions: ''
    name: Description
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  90922590-58f0-4a7e-abfb-8ca16b15ddef:
    contentColumnType: text
    fieldGroup: null
    handle: titleNetwork
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: contentNetwork
name: Content
sortOrder: 1
