field: 6b338a19-9dc3-4a10-9fa7-d324f5c60c4d
fieldLayouts:
  ee02f3d9-7253-48bc-a3ce-c7b6a611e12e:
    tabs:
      -
        elements:
          -
            fieldUid: 6afa1bc1-7908-4558-aa63-69cc006ff789
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d3ab2053-a86a-4b83-8ab5-8d7d99044d80
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6afa1bc1-7908-4558-aa63-69cc006ff789:
    contentColumnType: string
    fieldGroup: null
    handle: socialIcon
    instructions: ''
    name: 'Social icon'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Facebook
            -
              - value
              - 'fa fa-facebook-square'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Twitter
            -
              - value
              - 'fa fa-twitter'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - LinkedIn
            -
              - value
              - 'fa fa-linkedin-square'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  d3ab2053-a86a-4b83-8ab5-8d7d99044d80:
    contentColumnType: string(255)
    fieldGroup: null
    handle: socialUrl
    instructions: ''
    name: 'Social Url'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: socialLink
name: 'Social link'
sortOrder: 1
