field: 160d98c4-f407-4d6f-9d7c-9cd8afe4b7e9
fieldLayouts:
  9611d621-39a2-4327-8ea6-6ae603a43a0a:
    tabs:
      -
        elements:
          -
            fieldUid: 4a1775f7-e4ce-407f-b568-7fb63d019a03
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 19dd2ee0-1bff-4667-a021-39a787224265
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  19dd2ee0-1bff-4667-a021-39a787224265:
    contentColumnType: string(255)
    fieldGroup: null
    handle: socialLink
    instructions: 'Enter the URL to your social network page'
    name: URL
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  4a1775f7-e4ce-407f-b568-7fb63d019a03:
    contentColumnType: string
    fieldGroup: null
    handle: socialIcon
    instructions: 'Choose a social network'
    name: 'Social network'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Facebook
            -
              - value
              - 'fa fa-facebook-square'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Twitter
            -
              - value
              - 'fa fa-twitter'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Youtube
            -
              - value
              - 'fa fa-youtube-play'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Instagram
            -
              - value
              - 'fa fa-instagram'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Linked In'
            -
              - value
              - 'fa fa-linkedin'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: socialLink
name: 'Social network'
sortOrder: 1
