field: 5b285790-8f09-4d88-9df8-230f175d34aa
fieldLayouts:
  8c2c2d73-0ddf-49a1-a89f-66fd93a39b8e:
    tabs:
      -
        elements:
          -
            fieldUid: e2ef32d5-9e4a-4dd1-b376-0cab1161c731
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7f75ae24-1798-42cc-8a41-ccf9de55c6b9
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7f75ae24-1798-42cc-8a41-ccf9de55c6b9:
    contentColumnType: string(255)
    fieldGroup: null
    handle: topicUrl
    instructions: ''
    name: 'Topic url'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  e2ef32d5-9e4a-4dd1-b376-0cab1161c731:
    contentColumnType: text
    fieldGroup: null
    handle: topicName
    instructions: ''
    name: 'Topic name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: topicLinks
name: 'Topic links'
sortOrder: 1
