fieldLayouts:
  70d10c24-a19a-4923-b633-5226ef66e58b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: e7f18898-8c9a-4955-9c1e-b38d5a880bf0
            instructions: 'Add an existing or a new event'
            label: 'Add event'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: allEvents
hasTitleField: false
name: 'All events'
section: 0f71243b-9e6c-4805-9aaa-57ca02899e27
sortOrder: 1
titleFormat: 'All events'
titleTranslationKeyFormat: null
titleTranslationMethod: site
