fieldLayouts:
  af1e2707-126a-41ae-a9c3-7feb5fb6156f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: e0f343f5-bf12-49eb-b74e-b89a08a92090
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: homepage
hasTitleField: false
name: Homepage
section: 87a3d3d6-7170-474f-b761-21ff0fbcd43e
sortOrder: 1
titleFormat: Homepage
titleTranslationKeyFormat: null
titleTranslationMethod: site
