fieldLayouts:
  48905716-d0d8-4832-9e03-01dfbfe6fc28:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 7d99504c-6525-4350-977f-3a012170283b
            instructions: 'Choose an icon for social networks on this link https://fontawesome.com/icons?d=gallery. Write only the "class" value in this field. E.g. for "Facebook" write "fab fa-facebook".'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 96af4946-18b0-4070-af8d-42f1008055dc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: socialNetworks
hasTitleField: true
name: 'Social Networks'
section: 73ec1165-5e48-4a7a-825f-09248db5a22c
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
