fieldLayouts:
  bf6432ed-a44f-4842-a41c-c7d3e3332e57:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 5b285790-8f09-4d88-9df8-230f175d34aa
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: footerCategories
name: 'Footer categories'
siteSettings:
  0967bde6-f091-4666-b685-45e13bb32dee:
    hasUrls: true
    template: null
    uriFormat: 'footer-categories/{slug}'
structure:
  maxLevels: null
  uid: e820c7a4-c32a-49ca-9310-2e830aa03867
