fieldLayouts:
  35feebdf-adbc-4185-8fb6-a9d56fb4e04f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 5b285790-8f09-4d88-9df8-230f175d34aa
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: navigationTopics
name: 'Navigation topics'
siteSettings:
  0967bde6-f091-4666-b685-45e13bb32dee:
    hasUrls: true
    template: null
    uriFormat: 'navigation-topics/{slug}'
structure:
  maxLevels: null
  uid: a1952835-40ac-4add-b52d-778f936f3148
