fieldLayouts:
  51568600-c417-4c6a-a5ad-ce9e73447a7e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: pdfFiles
hasUrls: true
name: 'Pdf files'
settings:
  path: assets/presentations
sortOrder: 2
type: craft\volumes\Local
url: '@web/assets/presentations'
