contentColumnType: string
fieldGroup: bc989511-3fd9-4019-b7ab-663eeeedb1a6
handle: footerRightMenu
instructions: ''
name: 'Footer right menu'
searchable: false
settings:
  contentTable: '{{%matrixcontent_footerrightmenu}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
