contentColumnType: string
fieldGroup: bc989511-3fd9-4019-b7ab-663eeeedb1a6
handle: footerLeftMenu
instructions: ''
name: 'Footer left menu'
searchable: false
settings:
  contentTable: '{{%matrixcontent_footerleftmenu}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
