contentColumnType: string
fieldGroup: 6b1219ff-213c-4e36-abd9-4bba5cbe3f35
handle: footerLink
instructions: ''
name: 'Footer link'
searchable: false
settings:
  contentTable: '{{%matrixcontent_footerlink}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
