contentColumnType: string
fieldGroup: bc989511-3fd9-4019-b7ab-663eeeedb1a6
handle: menu
instructions: ''
name: Menu
searchable: false
settings:
  contentTable: '{{%matrixcontent_menu}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
