contentColumnType: text
fieldGroup: bc989511-3fd9-4019-b7ab-663eeeedb1a6
handle: showMoreLabel
instructions: ''
name: 'Show more label'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
