fieldLayouts:
  b70ca5f0-6f19-4193-927f-ff6c8c6c79ba:
    tabs:
      -
        elements:
          -
            fieldUid: 2a3f8c96-0aee-410f-868f-a675681c471f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 23b45aa3-721a-4395-9c74-59d4a180aa45
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 401c58db-239b-49c7-b873-bd05fdafa11c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 52d20310-6f48-427b-b799-39a76175f78a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 40267a4d-a478-4f62-a3d4-146cf4b6b9ca
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 02ce24bb-6c1c-4be2-91a7-3b7622a029d9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Labels
        sortOrder: 1
handle: layout
name: Layout
