enableVersioning: true
handle: entrEducation
name: 'Entrepreneuership education'
propagationMethod: all
siteSettings:
  0967bde6-f091-4666-b685-45e13bb32dee:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: entepreneurship-education
type: single
