enableVersioning: true
handle: footer
name: Footer
propagationMethod: all
siteSettings:
  0967bde6-f091-4666-b685-45e13bb32dee:
    enabledByDefault: true
    hasUrls: true
    template: common\footer
    uriFormat: footer
type: single
