enableVersioning: true
handle: navbar
name: Navbar
propagationMethod: all
siteSettings:
  0967bde6-f091-4666-b685-45e13bb32dee:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
