enableVersioning: true
handle: studentsInAction
name: 'Students in action'
propagationMethod: all
siteSettings:
  0967bde6-f091-4666-b685-45e13bb32dee:
    enabledByDefault: true
    hasUrls: true
    template: page\studentsInAction
    uriFormat: students-in-action
type: single
